export enum domain {
  UNAUTHENTICATED = "UNAUTHENTICATED",
  USER_EXISTS = "USER_ALREADY_EXISTS",
  TOKEN_VERIFICATION_ERROR = "TOKEN_VERIFICATION_ERROR",
  TOKEN_GENERATION_ERROR = "TOKEN_GENERATION_ERROR",
  FORBIDDEN = "FORBIDDEN",
}
